version: '3'

services:
  genesis_state:
    image: blocksphereid/idrp-node
    volumes:
      - ./genesis-state:/data
    command: >
      export-genesis-state
      --chain rococo
      /data/genesis-state
  
  genesis_wasm:
    image: blocksphereid/idrp-node
    volumes:
      - ./genesis-wasm:/data
    command: >
      export-genesis-wasm
      --chain rococo
      /data/genesis.wasm